apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-lot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: parking-lot
  template:
    metadata:
      labels:
        app: parking-lot
    spec:
      containers:
      - image: parking-lot.jar:latest
        name: parking-lot
        ports:
        - containerPort: 80
